name: Docker

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: argocd-plugin-helmfile

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{github.ref_name}}

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Push image to registry
        run: |
          IMAGE_ID=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{github.ref_name}}
          docker push $IMAGE_ID
          docker image tag $IMAGE_ID ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest 
          docker image push {{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
